### ISSUE TITLE
It‘s a great work! But how to install it? Can you write the install method in readme?Thank you .

### ISSUE THREAD

**Issue by renxiangbin** [kennibc/moodle-theme_fordson#1]

**Comment by kennibc** [comment]
Click on the button to "Clone or Download".  When downloaded to your computer, unzip it.  It should create a folder named "moodle-theme_fordson-master".  Rename the folder so that it is "fordson" (without quotes).  You can FTP that folder to your moodle site in /moodle/theme/ directory.  Or you can create a new ZIP file of the "fordson" folder and upload and install that.  My theme has been waiting for 37 days to be approved on Moodle.org.  Once that happens you can simply download from there.
